import{useEffect,useState}from"react";import{createClient}from"@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY,supabase=url&&key?createClient(url,key):null,digits=v=>String(v||"").replace(/\D/g,"");
export default function App(){const[session,setSession]=useState(null),[login,setLogin]=useState(""),[senha,setSenha]=useState(""),[recoveryPhone,setRecoveryPhone]=useState(""),[showRecoveryPhone,setShowRecoveryPhone]=useState(false),[recoverBusy,setRecoverBusy]=useState(false),[msg,setMsg]=useState(""),[view,setView]=useState("NOVA"),[data,setData]=useState({clientes:[],produtos:[],vendas:[],comissoes:[]}),[form,setForm]=useState({clienteId:"",produtoId:"",qtd:"",condicao:"7/14/21",observacao:""});
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(x=>setSession(x.data.session));return supabase.auth.onAuthStateChange((_,s)=>setSession(s)).data.subscription.unsubscribe},[]);
useEffect(()=>{if(!session)return;supabase.functions.invoke("mobile-vendas-externas",{body:{acao:"LISTAR"}}).then(({data,error})=>error?setMsg("NÃO FOI POSSÍVEL CARREGAR."):setData(data||{}))},[session]);
async function entrar(e){e.preventDefault();setMsg("ENTRANDO…");const id=login.trim().toLowerCase();let error;if(id.includes("@"))({error}=await supabase.auth.signInWithPassword({email:id,password:senha}));else{const r=await supabase.functions.invoke("login-cpf",{body:{cpf:digits(id),password:senha}});error=r.error;if(!error&&r.data?.access_token)({error}=await supabase.auth.setSession({access_token:r.data.access_token,refresh_token:r.data.refresh_token}))}setMsg(error?"CPF, E-MAIL OU SENHA INVÁLIDOS.":"")}
async function recuperar(){setShowRecoveryPhone(true);if(!login.trim())return setMsg("INFORME CPF OU E-MAIL.");if(!recoveryPhone.trim())return setMsg("INFORME O WHATSAPP CADASTRADO COM DDD.");setRecoverBusy(true);try{const{data,error}=await supabase.functions.invoke("recover-password-email",{body:{identificador:login.trim(),whatsapp:recoveryPhone.trim()}});if(error){let detail="NÃO FOI POSSÍVEL ENVIAR PELO WHATSAPP.";if(error.context instanceof Response){try{detail=(await error.context.clone().json()).error||detail}catch{}}setMsg(detail)}else setMsg(data.message)}catch{setMsg("VERIFIQUE A CONEXÃO E TENTE NOVAMENTE.")}finally{setRecoverBusy(false)}}
async function salvar(e){e.preventDefault();const{data:r,error}=await supabase.functions.invoke("mobile-vendas-externas",{body:{acao:"CRIAR_PROPOSTA",...form,qtd:Number(form.qtd)}});if(error)return setMsg("NÃO FOI POSSÍVEL ENVIAR A PROPOSTA.");setMsg("PROPOSTA ENVIADA PARA APROVAÇÃO.");setData(x=>({...x,vendas:[r,...(x.vendas||[])]}));setForm({clienteId:"",produtoId:"",qtd:"",condicao:"7/14/21",observacao:""})}
if(!supabase)return <main className="login"><section><h1>FORTE VENDA EXTERNA</h1><p>CONFIGURAÇÃO DA NUVEM PENDENTE.</p></section></main>;
if(!session)return <main className="login"><form onSubmit={entrar}><h1>FORTE VENDA EXTERNA</h1><p>ACESSO EXCLUSIVO DO VENDEDOR</p><input value={login} onChange={e=>setLogin(e.target.value)} placeholder="CPF OU E-MAIL"/><input type="password" value={senha} onChange={e=>setSenha(e.target.value)} placeholder="SENHA"/><button>ENTRAR</button>{showRecoveryPhone&&<label>WHATSAPP CADASTRADO COM DDD<input type="tel" autoComplete="tel" value={recoveryPhone} onChange={e=>setRecoveryPhone(e.target.value)} placeholder="DDD e número"/></label>}<button type="button" disabled={recoverBusy} onClick={recuperar}>{showRecoveryPhone?"ENVIAR LINK PELO WHATSAPP":"ESQUECI MINHA SENHA"}</button>{msg&&<small>{msg}</small>}</form></main>;
return <main><header><div><b>FORTE VENDA EXTERNA</b><small>SOMENTE SUAS VENDAS E CLIENTES</small></div><button onClick={()=>supabase.auth.signOut()}>SAIR</button></header><nav>{["NOVA","VENDAS","COMISSÕES"].map(x=><button className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>{view==="NOVA"&&<form className="card" onSubmit={salvar}><h2>NOVA PROPOSTA</h2><label>CLIENTE<select value={form.clienteId} onChange={e=>setForm({...form,clienteId:e.target.value})} required><option value="">SELECIONE…</option>{(data.clientes||[]).map(x=><option value={x.id}>{x.nome}</option>)}</select></label><label>PRODUTO<select value={form.produtoId} onChange={e=>setForm({...form,produtoId:e.target.value})} required><option value="">SELECIONE…</option>{(data.produtos||[]).map(x=><option value={x.id}>{x.nome} — {Number(x.preco||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</option>)}</select></label><label>QUANTIDADE<input type="number" min="1" value={form.qtd} onChange={e=>setForm({...form,qtd:e.target.value})} required/></label><label>CONDIÇÃO<input value={form.condicao} onChange={e=>setForm({...form,condicao:e.target.value})}/></label><label>OBSERVAÇÃO<textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><button>ENVIAR PARA APROVAÇÃO</button></form>}{view==="VENDAS"&&<section className="list">{(data.vendas||[]).map(x=><article><b>{x.numero||"PROPOSTA"}</b><span>{x.cliente}</span><span>{x.produto} • {x.qtd} UN</span><strong>{x.status||"AGUARDANDO APROVAÇÃO"}</strong></article>)}</section>}{view==="COMISSÕES"&&<section className="list">{(data.comissoes||[]).map(x=><article><b>{x.referencia}</b><span>{x.cliente}</span><strong>{Number(x.valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></article>)}</section>}{msg&&<div className="toast">{msg}</div>}</main>}
