import {customerName} from "./customer-name.js";
import{useEffect,useState}from"react";import{createClient}from"@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY,supabase=url&&key?createClient(url,key,{auth:{storage:window.localStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null,digits=v=>String(v||"").replace(/\D/g,"");
export default function App(){const[session,setSession]=useState(null),[login,setLogin]=useState(""),[senha,setSenha]=useState(""),[recoveryChannel,setRecoveryChannel]=useState("email"),[recoveryEmail,setRecoveryEmail]=useState(""),[recoveryPhone,setRecoveryPhone]=useState(""),[showRecoveryPhone,setShowRecoveryPhone]=useState(false),[recoverBusy,setRecoverBusy]=useState(false),[msg,setMsg]=useState(""),[view,setView]=useState("NOVA"),[data,setData]=useState({clientes:[],produtos:[],vendas:[],comissoes:[]}),[form,setForm]=useState({clienteId:"",produtoId:"",qtd:"",condicao:"7/14/21",observacao:""});
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(x=>setSession(x.data.session));return supabase.auth.onAuthStateChange((_,s)=>setSession(s)).data.subscription.unsubscribe},[]);
useEffect(()=>{if(!session)return;supabase.functions.invoke("mobile-vendas-externas",{body:{acao:"LISTAR"}}).then(({data,error})=>error?setMsg("NÃO FOI POSSÍVEL CARREGAR."):setData(data||{}))},[session]);
async function entrar(e){e.preventDefault();if(!/^\d{11}$/.test(digits(login))||!/^\d{6,}$/.test(senha))return setMsg("INFORME CPF E SENHA NUMÉRICA — MÍNIMO 6 DÍGITOS.");setMsg("ENTRANDO…");const id=login.trim().toLowerCase();let error;const r=await supabase.functions.invoke("login-cpf",{body:{cpf:digits(id),password:senha}});error=r.error;if(!error&&r.data?.access_token)({error}=await supabase.auth.setSession({access_token:r.data.access_token,refresh_token:r.data.refresh_token}));setMsg(error?"CPF OU SENHA INVÁLIDOS.":"")}
async function recuperar(){setShowRecoveryPhone(true);if(!/^\d{11}$/.test(digits(login)))return setMsg("INFORME O CPF CADASTRADO.");if(recoveryChannel==="whatsapp"&&!recoveryPhone.trim())return setMsg("INFORME O WHATSAPP CADASTRADO COM DDD.");if(recoveryChannel==="email"&&!recoveryEmail.trim())return setMsg("INFORME O E-MAIL CADASTRADO.");setRecoverBusy(true);try{const{data,error}=await supabase.functions.invoke("recover-password-email",{body:{identificador:digits(login),canal:recoveryChannel,email:recoveryEmail.trim(),whatsapp:recoveryPhone.trim()}});if(error){let detail="NÃO FOI POSSÍVEL ENVIAR O LINK.";if(error.context instanceof Response){try{detail=(await error.context.clone().json()).error||detail}catch{}}setMsg(detail)}else setMsg(data.message)}catch{setMsg("VERIFIQUE A CONEXÃO E TENTE NOVAMENTE.")}finally{setRecoverBusy(false)}}
async function salvar(e){e.preventDefault();const{data:r,error}=await supabase.functions.invoke("mobile-vendas-externas",{body:{acao:"CRIAR_PROPOSTA",...form,qtd:Number(form.qtd)}});if(error)return setMsg("NÃO FOI POSSÍVEL ENVIAR A PROPOSTA.");setMsg("PROPOSTA ENVIADA PARA APROVAÇÃO.");setData(x=>({...x,vendas:[r,...(x.vendas||[])]}));setForm({clienteId:"",produtoId:"",qtd:"",condicao:"7/14/21",observacao:""})}
if(!supabase)return <main className="login"><section><h1>FORTE VENDA EXTERNA</h1><p>CONFIGURAÇÃO DA NUVEM PENDENTE.</p></section></main>;
if(!session)return <main className="login"><form onSubmit={entrar}><h1>FORTE VENDA EXTERNA</h1><p>ACESSO EXCLUSIVO DO VENDEDOR</p><input value={login} onChange={e=>setLogin(digits(e.target.value).slice(0,11))} inputMode="numeric" maxLength={11} pattern="[0-9]{11}" placeholder="CPF"/><input type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" value={senha} onChange={e=>setSenha(digits(e.target.value))} placeholder="SENHA NUMÉRICA — MÍNIMO 6 DÍGITOS"/><button>ENTRAR</button>{showRecoveryPhone&&<><label>RECUPERAR POR<select value={recoveryChannel} onChange={e=>setRecoveryChannel(e.target.value)}><option value="email">E-MAIL</option><option value="whatsapp">WHATSAPP</option></select></label>{recoveryChannel==="email"?<label>E-MAIL CADASTRADO<input type="email" autoComplete="email" value={recoveryEmail} onChange={e=>setRecoveryEmail(e.target.value)}/></label>:<label>WHATSAPP CADASTRADO COM DDD<input type="tel" autoComplete="tel" value={recoveryPhone} onChange={e=>setRecoveryPhone(e.target.value)} placeholder="DDD e número"/></label>}</>}<button type="button" disabled={recoverBusy} onClick={recuperar}>{showRecoveryPhone?"ENVIAR LINK DE RECUPERAÇÃO":"CRIAR OU RECUPERAR SENHA"}</button>{msg&&<small>{msg}</small>}</form></main>;
return <main><header><div><b>FORTE VENDA EXTERNA</b><small>SOMENTE SUAS VENDAS E CLIENTES</small></div><div className="actions"><div data-forte-top-actions aria-label="Ações do sistema" /><button onClick={()=>supabase.auth.signOut()}>SAIR</button></div></header><nav>{["NOVA","VENDAS","COMISSÕES"].map(x=><button className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>{view==="NOVA"&&<form className="card" onSubmit={salvar}><h2>NOVA PROPOSTA</h2><label>CLIENTE — NOME FANTASIA<select value={form.clienteId} onChange={e=>setForm({...form,clienteId:e.target.value})} required><option value="">SELECIONE…</option>{(data.clientes||[]).map(x=><option value={x.id}>{customerName(x)}</option>)}</select></label><label>PRODUTO<select value={form.produtoId} onChange={e=>setForm({...form,produtoId:e.target.value})} required><option value="">SELECIONE…</option>{(data.produtos||[]).filter(x=>String(x.finalidade||"REVENDA").toUpperCase()==="REVENDA").sort((a,b)=>String(a.categoria||"OUTROS").localeCompare(String(b.categoria||"OUTROS"))||String(a.nome||"").localeCompare(String(b.nome||""))).map(x=><option value={x.id}>{String(x.categoria||"OUTROS").toUpperCase()} • {x.nome} — {Number(x.preco||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</option>)}</select></label><label>QUANTIDADE<input type="number" min="1" value={form.qtd} onChange={e=>setForm({...form,qtd:e.target.value})} required/></label><label>CONDIÇÃO<input value={form.condicao} onChange={e=>setForm({...form,condicao:e.target.value})}/></label><label>OBSERVAÇÃO<textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><button>ENVIAR PARA APROVAÇÃO</button></form>}{view==="VENDAS"&&<section className="list">{(data.vendas||[]).map(x=><article><b>{x.numero||"PROPOSTA"}</b><span>{customerName(x,data.clientes)}</span><span>{x.produto} • {x.qtd} UN</span><strong>{x.status||"AGUARDANDO APROVAÇÃO"}</strong></article>)}</section>}{view==="COMISSÕES"&&<section className="list">{(data.comissoes||[]).map(x=><article><b>{x.referencia}</b><span>{customerName(x,data.clientes)}</span><strong>{Number(x.valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></article>)}</section>}{msg&&<div className="toast">{msg}</div>}</main>}


export {supabase};
